/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Media item of issueDetail
 * @export
 * @interface IssueCommentMedia
 */
export interface IssueCommentMedia {
    /**
     * Origin type of media.
     * @type {string}
     * @memberof IssueCommentMedia
     */
    'originType'?: string;
    /**
     * Type of media
     * @type {string}
     * @memberof IssueCommentMedia
     */
    'type'?: IssueCommentMediaTypeEnum;
    /**
     * External URL of media
     * @type {string}
     * @memberof IssueCommentMedia
     */
    'url'?: string;
}

export const IssueCommentMediaTypeEnum = {
    Photo: 'PHOTO',
    Post: 'POST'
} as const;

export type IssueCommentMediaTypeEnum = typeof IssueCommentMediaTypeEnum[keyof typeof IssueCommentMediaTypeEnum];


