apiVersion: notification.halo.run/v1alpha1
kind: NotificationTemplate
metadata:
  name: template-new-comment-on-issue-message
spec:
  reasonSelector:
    reasonType: new-comment-on-issue-message
    language: default
  template:
    title: "[(${commenter})] 评论了你在 [(${issueMessageCreatedAt})] 时刻发布的issue"
    rawBody: |
      [(${subscriber.displayName})] 你好：

      [(${commenter})] 评论了你的issue“[(${issueMessageRawContent})]”， 以下是评论的具体内容：

      [(${content})]
    htmlBody: |
      <div class="notification-content">
        <div class="head">
          <p class="honorific" th:text="|${subscriber.displayName} 你好：|"></p>
        </div>
        <div class="body">
          <div>
            <div th:text="|${commenter} 评论了你的issue|"></div>
            <div>
              <a
               th:href="${issueMessageUrl}"
               target="_blank"
               style="display: block;font-style: italic;"
               th:utext="${issueMessageHtmlContent}"
              >
              </a>
            </div>
            <div>以下是评论的具体内容：</div>
          </div>
          <pre class="content" th:text="${content}"></pre>
        </div>
        <div></div>
      </div>
