# Refer https://docs.halo.run/developer-guide/plugin/basics/manifest

apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  # The name defines how the plugin is invoked, A unique name
  name: issues
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: webjing
    website: https://github.com/webjing
  logo: logo.png
  homepage: https://github.com/webjing/issues#readme
  repo: https://github.com/webjing/issues
  issues: https://github.com/webjing/issues/issues
  displayName: "issues"
  description: "issues - Halo 插件"
  license:
    - name: "GPL-3.0"
      url: "https://github.com/webjing/issues/blob/main/LICENSE"
