apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginIssues
spec:
  enabled: true
  requires: ">=2.23.0"
  author:
    name: webjing
    website: https://www.webjing.cn
  logo: logo.png
  homepage: https://github.com/wenjing-xin/plugin-issues#readme
  repo: https://github.com/wenjing-xin/plugin-issues
  issues: https://github.com/wenjing-xin/plugin-issues/issues
  displayName: "言答Issue"
  description: "这是一个专门为halo2.0提供的issue插件，可用于产品QA、问答交流"
  configMapName: plugin-issues-configmap
  settingName: plugin-issues-settings
  license:
    - name: "GPL-3.0"
      url: "https://github.com/wenjing-xin/halo-immich/blob/main/LICENSE"
