/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.21.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 *
 * @export
 * @interface TemplateField
 */
export interface TemplateField {
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'defaultValue'?: string;
    /**
     *
     * @type {{ [key: string]: string; }}
     * @memberof TemplateField
     */
    'fieldOptions'?: Array<{ [key: string]: string; }>;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'helpText'?: string;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'key': string;
    /**
     *
     * @type {number}
     * @memberof TemplateField
     */
    'maxLength'?: number;
    /**
     *
     * @type {number}
     * @memberof TemplateField
     */
    'minLength'?: number;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'placeholder'?: string;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'requiredMode'?: string;
    /**
     *
     * @type {number}
     * @memberof TemplateField
     */
    'rows'?: number;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'title': string;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'type': TemplateFieldTypeEnum;
    /**
     *
     * @type {string}
     * @memberof TemplateField
     */
    'validate'?: string;
}

export const TemplateFieldTypeEnum = {
    Text: 'TEXT',
    TextArea: 'TEXT_AREA',
    Select: 'SELECT',
    Radio: 'RADIO',
    Password: 'PASSWORD',
    Email: 'EMAIL'
} as const;

export type TemplateFieldTypeEnum = typeof TemplateFieldTypeEnum[keyof typeof TemplateFieldTypeEnum];


