/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * rendered medium
 * @export
 * @interface IssueMedia
 */
export interface IssueMedia {
    /**
     * Origin type of media.
     * @type {string}
     * @memberof IssueMedia
     */
    'originType'?: string;
    /**
     * Type of media
     * @type {string}
     * @memberof IssueMedia
     */
    'type'?: IssueMediaTypeEnum;
    /**
     * External URL of media
     * @type {string}
     * @memberof IssueMedia
     */
    'url'?: string;
}

export const IssueMediaTypeEnum = {
    Photo: 'PHOTO',
    Post: 'POST'
} as const;

export type IssueMediaTypeEnum = typeof IssueMediaTypeEnum[keyof typeof IssueMediaTypeEnum];


