/* tslint:disable */
/* eslint-disable */
/**
 * Halo
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 2.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * Media item of issueDetail
 * @export
 * @interface IssueDetailMedia
 */
export interface IssueDetailMedia {
    /**
     * Origin type of media.
     * @type {string}
     * @memberof IssueDetailMedia
     */
    'originType'?: string;
    /**
     * Type of media
     * @type {string}
     * @memberof IssueDetailMedia
     */
    'type'?: IssueDetailMediaTypeEnum;
    /**
     * External URL of media
     * @type {string}
     * @memberof IssueDetailMedia
     */
    'url'?: string;
}

export const IssueDetailMediaTypeEnum = {
    Photo: 'PHOTO',
    Post: 'POST'
} as const;

export type IssueDetailMediaTypeEnum = typeof IssueDetailMediaTypeEnum[keyof typeof IssueDetailMediaTypeEnum];


